//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arenda
    {
        public int Id { get; set; }
        public int IdClienta { get; set; }
        public int IdTs { get; set; }
        public System.DateTime DataVzyatie { get; set; }
        public string SrokArenda { get; set; }
        public int IdStatus { get; set; }
        public string Komentarii { get; set; }
        public int IdPolzovatelya { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Polzovateli Polzovateli { get; set; }
        public virtual StatusZayavki StatusZayavki { get; set; }
        public virtual TransportnoeSredstvo TransportnoeSredstvo { get; set; }
    }
}
