//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSkidka
    {
        public int IdSkidki { get; set; }
        public int IdClienta { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Skidka Skidka { get; set; }
    }
}
