//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendWpfApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArendaEntities : DbContext
    {
        public ArendaEntities()
            : base("name=ArendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static ArendaEntities _context;
        public static ArendaEntities GetContext()
        {
            if (_context == null)
                _context = new ArendaEntities();
            return _context;
        }
        public virtual DbSet<Arenda> Arenda { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientSkidka> ClientSkidka { get; set; }
        public virtual DbSet<Cvet> Cvet { get; set; }
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Polzovateli> Polzovateli { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Skidka> Skidka { get; set; }
        public virtual DbSet<StatusZayavki> StatusZayavki { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipBenzina> TipBenzina { get; set; }
        public virtual DbSet<TipKPP> TipKPP { get; set; }
        public virtual DbSet<TipKuzova> TipKuzova { get; set; }
        public virtual DbSet<TransportnoeSredstvo> TransportnoeSredstvo { get; set; }
    }
}
