//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportnoeSredstvo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportnoeSredstvo()
        {
            this.Arenda = new HashSet<Arenda>();
            this.Class = new HashSet<Class>();
            this.Cvet = new HashSet<Cvet>();
        }
    
        public int Id { get; set; }
        public string RegNomerTS { get; set; }
        public int IdMarka { get; set; }
        public int IdModel { get; set; }
        public int IdTipKuzova { get; set; }
        public int IdTransmisii { get; set; }
        public int KolichestvoDverei { get; set; }
        public int IdTipBenzina { get; set; }
        public int GodVipuska { get; set; }
        public int Probeg { get; set; }
        public int StoimostZaSutki { get; set; }
        public int StoimostZaChas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arenda> Arenda { get; set; }
        public virtual Marka Marka { get; set; }
        public virtual Model Model { get; set; }
        public virtual TipBenzina TipBenzina { get; set; }
        public virtual TipKPP TipKPP { get; set; }
        public virtual TipKuzova TipKuzova { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cvet> Cvet { get; set; }
    }
}
